### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by pocesar** [browserify/static-eval#20]
https://npmjs.com/advisories/758

**Comment by cript0nauta** [comment]
#21 fixes the security issue

**Comment by davidemontanari** [comment]
@substack Can you please take a look?

**Comment by nullivex** [comment]
Despite the release 4 hours ago, this remains applicable. Is that a mistake?

Thank you for the quick response!

**Comment by mheggeseth** [comment]
> #21 fixes the security issue

Turns out [it doesn't](https://github.com/browserify/static-eval/pull/21#issuecomment-464769708) due to scoping issues. #23 is the intended fix.

**Comment by millette** [comment]
Now that #23 is merged into 2.0.2, is there another step to clear the [advisory](https://npmjs.com/advisories/758) which is still in effect? I ran `npm audit fix`, new version was picked up, but the advisory remains.

**Comment by nullivex** [comment]
Similar behavior here!

**Comment by jrbattles** [comment]
We are experiencing the same thing.  My application has to pass npm audit for regulatory compliance.  please advise.

**Comment by millette** [comment]
I've run the proof on concept with **2.0.1** and the output is the whole set of environment variables. Upgrading to **2.0.2** outputs `undefined` instead so that's great.

First, create the index file in a new directory.

index:js:
```js
var evaluate = require('static-eval');
var parse = require('esprima').parse;

var src = process.argv[2];
var payload = '(function({x}){return x.constructor})({x:"".sub})("console.log(process.env)")()'
var ast = parse(payload).body[0].expression;
console.log(evaluate(ast, {x:1}));
```

Then create the package file with deps (using `static-eval@2.0.1` first):

```sh
cd NEW-DIR # where you created index.js
npm init -y
npm install static-eval@2.0.1 esprima
node .
```

Should output environment variables, which we wanted to prevent by using static-eval.

```sh
npm install static-eval@2.0.2
node .
```

Should only output `undefined`, success!

Who can update the advisory?

**Comment by joebowbeer** [comment]
Updated

**Comment by millette** [comment]
Ping; closing time :-)
